---
# tasks file for nginx
- block:
  - name: Install nginx
    apt:
      name: nginx
      state: latest
  - name: Enable autoload
    service:
     name: nginx
     enabled: yes
     state: started
  when: ansible_os_family == "Debian"

- block:
  - name: Install nginx
    yum:
      name: nginx
      state: latest
  - name: Enable autoload
    service:
     name: nginx
     enabled: yes
     state: started
  when: ansible_os_family == "RedHat"