---
  all:
    children: 
      monitoring:
        hosts:
          ubuntu:
            ansible_host: 3.120.235.2
            roles:
            #  - atop
            #  - curl
            #  - htop
            #  - iftop
              - jenkins
            #  - letsencrypt
              - nginx
            #  - snmp
            #  - vim
            #  - wget 
             
             
            ansible_ssh_private_key_file: ~/.ssh/key.pem
            ansible_user: ubuntu
            ansible_port: 22
            ansible_python_interpreter: /usr/bin/python3
            admin_email: sleptsovilya@gmail.com 
            domain_name: isd.pp.ua
            
          centos:
            ansible_host: 35.228.137.124
            roles:
            #  - epel-release
            #  - atop
            #  - curl
            #  - htop
            #  - iftop
            #  - jenkins
            #  - letsencrypt
            #  - nginx
            #  - snmp
            #  - vim
            #  - wget
                      
            ansible_ssh_private_key_file: ~/.ssh/google
            ansible_user: sleptsovilya
            ansible_port: 22
            

    vars:
      ansible_become: yes
      ansible_become_method: sudo