---
  all:
    children: 
      monitoring:
        hosts:
          ubuntu:
            ansible_host: 35.158.81.70
            roles:
             - atop
             - curl
             - epel-release
             - htop
             - iftop
             - jenkins
             - nginx
             - snmp
             - vim
             - wget
             
            ansible_ssh_private_key_file: ~/.ssh/key.pem
            ansible_user: ubuntu
            ansible_port: 22
            ansible_python_interpreter: /usr/bin/python3
          centos:
            ansible_host: 35.228.137.124
            roles:
             - atop
             - curl
             - epel-release
             - htop
             - iftop
             - jenkins
             - nginx
             - snmp
             - vim
             - wget
                      
            ansible_ssh_private_key_file: ~/.ssh/google
            ansible_user: sleptsovilya
            ansible_port: 22
            #ansible_python_interpreter: /usr/bin/python3

    vars:
      ansible_become: yes
      ansible_become_method: sudo