---
  all:
    children: 
      monitoring:
        hosts:
          ubuntu:
            ansible_host: 35.158.97.245
            roles:
              - atop
              - curl
              - htop
              - iftop
              - snmp
              - vim
              - wget
            ansible_ssh_private_key_file: ~/.ssh/key.pem
            ansible_user: ubuntu
            ansible_port: 22
          centos:
            ansible_host: 52.57.143.116
            roles:
              - curl
              - htop
              - iftop
              - snmp
              - vim
              - wget
              - atop             
            ansible_ssh_private_key_file: ~/.ssh/key.pem
            ansible_user: ec2-user
            ansible_port: 22

    vars:
      ansible_become: yes
      ansible_become_method: sudo