---
  all:
    children: 
      monitoring:
        hosts:
          ubuntu:
            ansible_host: 52.58.244.113
            roles:
             - nginx
            ansible_ssh_private_key_file: ~/.ssh/key.pem
            ansible_user: ubuntu
            ansible_port: 22
            ansible_python_interpreter: /usr/bin/python3
          centos:
            ansible_host: 54.93.252.28
            roles:
              - jenkins          
            ansible_ssh_private_key_file: ~/.ssh/key.pem
            ansible_user: ec2-user
            ansible_port: 22
            ##ansible_python_interpreter: /usr/bin/python3

    vars:
      ansible_become: yes
      ansible_become_method: sudo