---
# tasks file for atop
- block:
  - name: Install Iftop for Debian OS
    apt:
      name: "{{ packages }}"
    vars: 
     packages:
     - libc6
     - libgcc1
     - libncurses5
     - libtinfo5
     - lsb-base
     - zlib1g
    update_cache: yes
  when: ansible_os_family == "Debian"

- block:
  - name: Install Atop for RedHat OS
    yum: name=atop state=latest  
  when: ansible_os_family == "RedHat"