---
# tasks file for jenkins
- block:
   - name: Install  Java
     apt: name=openjdk-8-jre state=latest

   - name: Import the GPG keys of the Jenkins repository
     apt_key:
       url: https://pkg.jenkins.io/debian/jenkins.io.key
       state: present

   - name: Download jenkins.repo
     apt_repository:
       repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
       state: present


   - name: Install Jenkins
     apt: name=jenkins state=latest

   - name: Get init password Jenkins
     shell: cat /var/lib/jenkins/secrets/initialAdminPassword
     changed_when: false
     register: result

   - name: Remove default jenkins config
     file: name=/etc/default/jenkins state=absent

   - name: Install system nginx config
     template:
      src: templates/jenkins.j2
      dest: /etc/default/jenkins
   
  when: ansible_os_family == "Debian"

- block:
   - name: Install Java
     yum: name=java-1.8.0-openjdk state=latest

   - name: Ensure Jenkins Repository is Installed
   
     yum_repository:
        name: jenkins
        state: present
        description: Official Jenkins Yum Repo
        baseurl: http://pkg.jenkins.io/redhat
        gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        gpgcheck: yes
        enabled: yes

   - name: Install Jenkins
     yum:
       name: jenkins
       state: latest
   
   - name: Enable and Start the Jenkins Service
     service:
        name: jenkins
        enabled: yes
        state: started
  when: ansible_os_family == "RedHat"