---
# tasks file for iftop
- block:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Install Iftop for Debian OS
    apt:
      name: "{{ packages }}"
    vars:
     packages:
     - libpcap0.8
     - libpcap0.8-dev
     - libncurses5
     - libncurses5-dev
  when: ansible_os_family == "Debian"

- block:
  
  - name: Install Iftop for RedHat OS
    yum: name=iftop state=latest
    
  
    
  when: ansible_os_family == "RedHat"